### ISSUE TITLE
Require specific versions of drivers

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/ffnvcodec-headers-feedstock#7]
@jakirkham I think this package needs to depend on driver versions on the OS.

Is there a way to pin to different CUDA/NVidia driver versions?

**Comment by hmaarrfk** [comment]
Documetnation can be found:
https://github.com/FFmpeg/nv-codec-headers

on the minimum versions.

**Comment by sdvillal** [comment]
Could virtual packages help here?
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html

**Comment by hmaarrfk** [comment]
Are you suggesting to use cuda as a proxy for the driver version?

**Comment by jakirkham** [comment]
Not that I'm aware of. We discussed generalizing virtual packages in Conda issue ( https://github.com/conda/conda/issues/10131 ), which may be useful for addressing this need

cc @chenghlee @kkraus14 (for vis)

**Comment by hmaarrfk** [comment]
I don't think this is needed ffmpeg is smart enough to error gracefully if the right driver isn't installed.
